### PR TITLE
Changed behavior of --diffbase

### LINKED ISSUE #17: Improve --diffbase to use branching off point

### PR DESCRIPTION
**Pull request by justbuchanan**
Before when doing `stylize --diffbase master`, stylize would format any file that on your branch that differs from the master branch.  This caused some weirdness when files were changed on master since you branched off from it, causing files to be formatted that you didn't change on your branch.

The new behavior finds the most recent ancestor between your branch and the branch/commit specified by `--diffbase`.  This ensures that only files that you've changed since branching off get formatted.

closes #17 

cc @jgkamat

### CODE REVIEW

**Comment by jgkamat** [comment]
🎉 nice!

If the diffbase target isn't an ancestor this won't fail, right? Otherwise 👍

**Comment by justbuchanan** [comment]
It looks at the most recent ancestor _between_ the diffbase target and the current HEAD.  This should be the "branching off point" of your branch relative to master.  It should never fail to find an ancestor.

**Comment by jgkamat** [comment]
There could be this case (unlikely, but it could happen):

```
 o -> o -> o -> o
         HEAD   ^
                |
o -> o -> o ->  o
  DIFFBASE
```

Where two branches don't share a common ancestor. This can happen when using `subtree` to merge git repos, or using `--orphan` in various places (checkout?) in git to create a new unrelated commit. I just didn't want that to be undefined behavior 😉

**Comment by justbuchanan** [comment]
Yeah I guess you're right, it should probably give a warning in that case.  I'll add it to the todo list.

**Pull request merged**
